### ISSUE TITLE
md5 namespace collision

### ISSUE THREAD

**Issue by maphew** [maphew/apt#13]
There is a function `md5` and a global variable `md5`. One of them has to go.

**Comment by amr66** [comment]
It's a good praxis to "hide" variables by using underscores, may be that's a way? If all global variables would be marked that way, identifying them in the code will be much easier. So i'd vote for __md5!

**Comment by maphew** [comment]
...also discovered there's a standard md5 module! Commit ba079337e6927a1938386134bf3d7b41475f06aa changes the md5 command to `apt hascheck`.

a quick and standardized visual indicator of global variables is a good idea. I tend not to like underscores, don't like the finger stretch when typing, but don't have any better ideas. Punting this part of the discussion down the road; it'll get it's own issue ticket.

**Comment by amr66** [comment]
hashcheck or hascheck?
