### ISSUE TITLE
apt.py crashes on reading setup.ini with no 'install' key

### ISSUE THREAD

**Issue by amr66** [maphew/apt#24]
With the last update() of setup.ini i recognized that grass71-devel has no entry for install.
So in parse_setup_ini() this will cause an KeyError Exception:

d['zip_path'],d['zip_size'],d['md5'] = d['install'].split()

you could change it to
try:
            d['zip_path'],d['zip_size'],d['md5'] = d['install'].split()
except KeyError:
            print "warning: ", d['name'],  "has no entry install"
            d['zip_path'],d['zip_size'],d['md5'] = ('','','')

But this causes errors later, if one tries to access that information, e.g. on download/install

**Comment by amr66** [comment]
You did something similar in get_info():
    if 'install' in d.keys():
        # 'install' and 'source keys have compound values, atomize them
        d['zip_path'],d['zip_size'],d['md5'] = d['install'].split()
        if not debug:
            del d['install']

**Comment by maphew** [comment]
Thanks for this report. I noticed the key error yesterday but didn't have time to track it down (and wasn't looking forward to it since I that it was me that broke something, not something different from upstream!). 

We should handle the problem better, but it's a relief it didn't start here :)

**Comment by maphew** [comment]
added a ticket upstream http://trac.osgeo.org/osgeo4w/ticket/457
