### ISSUE TITLE
command line option -r --root

### ISSUE THREAD

**Issue by amr66** [maphew/apt#39]
is not considered. Could be done in check_env(), would be a good thing if doing a apt setup and no environment variable has been set yet. Anyway, it exists, so it should do something.

**Comment by maphew** [comment]
related is disabled code near line ~1816, *#disabled pending argparse/whatever implementation*
https://github.com/maphew/apt/blob/master/apt.py#L1816

I don't remember at the moment why I turned it off, it didn't work completely/reliably. I would like to not have to set an environment variable first though. Thanks for the ticket.

**Comment by maphew** [comment]
closed in merge #42
